springdoc:
  show-actuator: 'true'
spring:
  datasource:
    show-sql: 'true'
    username: postgres
    password: 1234
    url: jdbc:postgresql://172.17.47.60:5432/irradiation_db
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: ${PORT:8080}
  cors: false
  error:
    include-stacktrace: never
    include-exception: 'false'
    include-binding-errors: always
    include-message: always

# Logging Level
logging:
  level:
    br:
      com:
        mobiis: DEBUG
