springdoc:
  show-actuator: 'true'
server:
  address: 0.0.0.0
  port: ${PORT:8080}
  cors: true
  error:
    include-stacktrace: never
    include-exception: 'false'
    include-binding-errors: always
    include-message: always
spring:
  web:
    cors:
      allowed-origins: '*'
      allowed-methods: '*'
      allowed-headers: '*'
  datasource:
    show-sql: 'true'
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher