spring:
  profiles:
    active: dev
  web:
    locale: pt-BR
    locale-resolver: fixed
management:
  endpoints:
    web:
      exposure:
        include: health,env,metrics
  endpoint:
    health:
      show-details: always